version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: backend/
    networks:
      - aiapi_net
    ports: 
      - 8080:80
  db:
    container_name: db
    image: postgres
    networks:
      - aiapi_net
    ports: 
      - 7979:5432
    environment:
      - POSTGRES_DB=aiapi
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=c0cac0la
  dbgui:
    container_name: dbgui
    image: adminer
    networks:
      - aiapi_net
    ports:
     - 7878:8080
  ts:
    container_name: ts
    image: tensorflow/serving
    networks:
      - aiapi_net
    ports:
      - 7777:8501
    volumes:
      - ./tensorflow/:/models/
    command: >-
      --model_config_file=/models/models.config
      --model_config_file_poll_wait_seconds=60
  
  
# By creating a vlan for all of the microservices, we can reference each one by it's
# container name instead of IP address in all of our code
networks:
  aiapi_net:
    name: aiapi_net
    driver: bridge
