version: '3.8'

services:
  ts:
    container_name: ts
    image: tensorflow/serving
    ports:
      - 8501:8501
    volumes:
      - /Users/martin/Documents/GitHub/ai-api/Models/:/models/
    command: >-
      --model_config_file=/models/models.config
      --model_config_file_poll_wait_seconds=60
  
  db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=aiapi
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password